# Generated by Django 2.2.7 on 2019-12-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=459),
        ),
    ]
