# Generated by Django 2.2.7 on 2019-12-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0003_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.FileField(default='avatar.png', upload_to='images/'),
        ),
    ]
