# Generated by Django 2.2.7 on 2019-12-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0004_auto_20191216_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.FileField(default='img/avatar.png', upload_to='img/'),
        ),
    ]
