# Generated by Django 2.2.7 on 2019-12-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0005_auto_20191216_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='foodbolg/img/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.FileField(default='foodbolg/img/avatar.png', upload_to='foodbolg/img/'),
        ),
    ]
