# Generated by Django 2.2.7 on 2019-12-20 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0006_auto_20191220_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodblog.User')),
            ],
        ),
    ]
